### ISSUE TITLE
I would like to do my website by inspired yours

### ISSUE THREAD

**Issue by STnetwork** [CharlesFeng47/charlesfeng.cn#1]
Hi,

I'm beginners in Gatsby, Ans I like your theme, could you help me to have a base of your website for my own ?

Thanks in advance.

**Comment by CharlesFeng47** [comment]
I'm sorry about not checking my email inbox until yesterday.

I have updated some basic info in the README and I think it would help you to understand this project. However, you should refer to the [Gatsby offical website](https://www.gatsbyjs.org/docs/) if you wanna know something detail about Gatsby.
